### ISSUE TITLE
[FEATURE] Delområder to grunnkrets

### ISSUE THREAD

**Issue by alfredbirk** [alfredbirk/SmartCity#33]

**Comment by mariusaarsnes** [comment]
Missing data about delområder.

I have asked Vegard if Mobility Analytics have access to it.

**Comment by mariusaarsnes** [comment]
Received data for statistical tracts from Mobility Analytics. However, the data on basic statistical units we have been using is missing one unit. I have asked Ørjan if he can send over their data on basic statistical units so that we do not have to use a third party source. This data may also match better with the statistical tracts
